
createSummary <- function(digits) {
	ds <- read.csv("feature_table.csv")
	ds[mapply(is.infinite, ds)] <- NA #change all inf to NA
	cpd <- ds[complete.cases(ds$commits_per_dev),] #for commits per dev, we can't handle the NA so we remove them
	pr <- ds[complete.cases(ds$pr_ratio),] #do the same for pull request ratio

	summaryData <- data.frame(Feature = character(13), Minimum = numeric(13), Maximum = numeric(13), Average = numeric(13), Median = numeric(13), stringsAsFactors=FALSE)

	summaryData$Feature[1] <- as.character("Commits per dev")
	summaryData$Feature[2] <- as.character("Forks")
	summaryData$Feature[3] <- as.character("Pull requests")
	summaryData$Feature[4] <- as.character("Contributors")
	summaryData$Feature[5] <- as.character("Project age")
	summaryData$Feature[6] <- as.character("Average followers")
	summaryData$Feature[7] <- as.character("Maximum followers")
	summaryData$Feature[8] <- as.character("Commits per day")
	summaryData$Feature[9] <- as.character("Pull request ratio")
	summaryData$Feature[10] <- as.character("Members per organization")
	summaryData$Feature[11] <- as.character("Average followers organization")
	summaryData$Feature[12] <- as.character("Maximum followers organization")
	summaryData$Feature[13] <- as.character("Stars")

	summaryData$Minimum[1] <- min(cpd$commits_per_dev)
	summaryData$Maximum[1] <- max(cpd$commits_per_dev)
	summaryData$Average[1] <- mean(cpd$commits_per_dev)
	summaryData$Median[1] <- median(cpd$commits_per_dev)
	summaryData$Minimum[2] <- min(ds$forks)
	summaryData$Maximum[2] <- max(ds$forks)
	summaryData$Average[2] <- mean(ds$forks)
	summaryData$Median[2] <- median(ds$forks)
	summaryData$Minimum[3] <- min(ds$pull_requests)
	summaryData$Maximum[3] <- max(ds$pull_requests)
	summaryData$Average[3] <- mean(ds$pull_requests)
	summaryData$Median[3] <- median(ds$pull_requests)
	summaryData$Minimum[4] <- min(ds$contributors)
	summaryData$Maximum[4] <- max(ds$contributors)
	summaryData$Average[4] <- mean(ds$contributors)
	summaryData$Median[4] <- median(ds$contributors)
	summaryData$Minimum[5] <- min(ds$age)
	summaryData$Maximum[5] <- max(ds$age)
	summaryData$Average[5] <- mean(ds$age)
	summaryData$Median[5] <- median(ds$age)
	summaryData$Minimum[6] <- min(ds$avg_followers)
	summaryData$Maximum[6] <- max(ds$avg_followers)
	summaryData$Average[6] <- mean(ds$avg_followers)
	summaryData$Median[6] <- median(ds$avg_followers)
	summaryData$Minimum[7] <- min(ds$max_followers)
	summaryData$Maximum[7] <- max(ds$max_followers)
	summaryData$Average[7] <- mean(ds$max_followers)
	summaryData$Median[7] <- median(ds$max_followers)
	summaryData$Minimum[8] <- min(ds$commits_per_day)
	summaryData$Maximum[8] <- max(ds$commits_per_day)
	summaryData$Average[8] <- mean(ds$commits_per_day)
	summaryData$Median[8] <- median(ds$commits_per_day)
	summaryData$Minimum[9] <- min(pr$pr_ratio)
	summaryData$Maximum[9] <- max(pr$pr_ratio)
	summaryData$Average[9] <- mean(pr$pr_ratio)
	summaryData$Median[9] <- median(pr$pr_ratio)
	summaryData$Minimum[10] <- min(ds$members_per_organization)
	summaryData$Maximum[10] <- max(ds$members_per_organization)
	summaryData$Average[10] <- mean(ds$members_per_organization)
	summaryData$Median[10] <- median(ds$members_per_organization)
	summaryData$Minimum[11] <- min(ds$average_followers_organization)
	summaryData$Maximum[11] <- max(ds$average_followers_organization)
	summaryData$Average[11] <- mean(ds$average_followers_organization)
	summaryData$Median[11] <- median(ds$average_followers_organization)
	summaryData$Minimum[12] <- min(ds$max_followers_organization)
	summaryData$Maximum[12] <- max(ds$max_followers_organization)
	summaryData$Average[12] <- mean(ds$max_followers_organization)
	summaryData$Median[12] <- median(ds$max_followers_organization)
	summaryData$Minimum[13] <- min(ds$stars)
	summaryData$Maximum[13] <- max(ds$stars)
	summaryData$Average[13] <- mean(ds$stars)
	summaryData$Median[13] <- median(ds$stars)

	#Round numeric values
	is.num <- sapply(summaryData, is.numeric)
	summaryData[is.num] <- lapply(summaryData[is.num], round, digits)

	print(summaryData, digits = digits)

	summaryData #return it
}